# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: AliyunDrive-Pro-API-OnGithubAction

on:
  workflow_dispatch:
  repository_dispatch:
   types: [AliyunDrive-Pro-API-OnGithubAction]
  push:
    branches: 
    - main
  schedule:
    - cron: "0 2 * * *"


jobs:
  Check-in:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: 3.12
    - name: "Set up requests"
      run: |
       pip install requests
    - name: "run main.py"
      env:
        email: ${{secrets.email}}
        password: ${{secrets.password}}
        account_id: ${{secrets.account_id}}
      run: |
        python main.py
